server:
  port: 7001

spring:
  application:
    name: Eureka-server7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
    defaultZone: http://eureka7000.com:7000/eureka   # 集群版

